### ISSUE TITLE
homebridge getting very slow or timeout after homebridge-broadlink-sp installed

### ISSUE THREAD

**Issue by syu-lk4b** [smka/homebridge-broadlink-sp#5]
does anyone face the same issue as me, not sure if the compatible issue with others or that's because of the bug, after I install this module to control my sp-mini3 power plug, my homebridge is getting very slow when long time not using it. meaning after a while not using the homekit, it will take either too long to fetching the status or just timeout. but once connected, it function very well. not really sure what's going on. From the output log, even in the debug mode, I didn't find anything really useful. 

here is all log related with broadlink

May 30 06:25:45 stevenhomesmart homebridge[20491]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:4:48)
May 30 06:25:45 stevenhomesmart homebridge[20491]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/index.js:1:90)
May 30 06:25:45 stevenhomesmart homebridge[20491]: [5/30/2017, 6:25:45 AM] Loaded plugin: homebridge-broadlink-sp
May 30 06:25:45 stevenhomesmart homebridge[20491]: [5/30/2017, 6:25:45 AM] Registering accessory 'homebridge-broadlink-sp.broadlinkSP'
May 30 06:25:47 stevenhomesmart homebridge[20491]: [5/30/2017, 6:25:47 AM] [My Broadlink SP3] Initializing broadlinkSP accessory...
May 30 09:57:27 stevenhomesmart homebridge[16087]: [5/30/2017, 9:57:27 AM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
May 30 09:57:27 stevenhomesmart homebridge[16087]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:4:48)
May 30 09:57:27 stevenhomesmart homebridge[16087]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/index.js:1:90)
May 30 09:57:27 stevenhomesmart homebridge[16087]: [5/30/2017, 9:57:27 AM] Loaded plugin: homebridge-broadlink-sp
May 30 09:57:27 stevenhomesmart homebridge[16087]: [5/30/2017, 9:57:27 AM] Registering accessory 'homebridge-broadlink-sp.broadlinkSP'
May 30 09:57:29 stevenhomesmart homebridge[16087]: [5/30/2017, 9:57:29 AM] [My Broadlink SP3] Initializing broadlinkSP accessory...
May 30 10:05:47 stevenhomesmart homebridge[17270]: [5/30/2017, 10:05:47 AM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
May 30 10:05:47 stevenhomesmart homebridge[17270]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:4:48)
May 30 10:05:47 stevenhomesmart homebridge[17270]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/index.js:1:90)
May 30 10:05:47 stevenhomesmart homebridge[17270]: [5/30/2017, 10:05:47 AM] Loaded plugin: homebridge-broadlink-sp
May 30 10:05:47 stevenhomesmart homebridge[17270]: [5/30/2017, 10:05:47 AM] Registering accessory 'homebridge-broadlink-sp.broadlinkSP'

and besides the broadlink I have xiaomi devices

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "accessories" :[
	{
  	"accessory": "PiTemperature",
  	"name": "Raspberry PI Temperature"
	}
	],
    "platforms": [
        {
          "platform": "AqaraPlatform",
          "sid": ["286c07858cc6"],
          "password": ["c7vf3vxe4kc5m6o7"],
          "fakeLightBulbForLightSwitch": true
        },
        {
          "platform" : "yeelight",
          "name" : "yeelight"
        },
        {
          "platform" : "XiaomiMiio",
          "name" : "XiaomiMiio",
          "pollChanges": true,
          "pollInterval": 15,
          "searchInterval": 1800
          }
              ]
}

**Comment by syu-lk4b** [comment]
i am pretty sure now. after removing this module from my config.json , everything back to normal now.  any idea?

**Comment by NicChrist** [comment]
I have a similar problem with my 	BroadLink-SPmini-T1. I can switch the plug a few times via the HomeKit App but then it loses the connection. I have wait a while or restart the homebridge process to get it working again. It seems like homebridge is freezing/getting a timeout.
This is how my config.json looks like:
```
{
   "bridge":{
      "name":"Homebridge",
      "username":"CC:22:3D:E3:CE:35",
      "port":51826,
      "pin":"031-45-154"
   },
   "accessories":[
        {
            "accessory": "PiTemperature",
            "name": "Raspberry PI Temperature"
        },
        {
            "accessory": "broadlinkSP",
            "name": "Smart Plug",
            "mac": "34:EA:34:F1:4A:8D"
        },
        {
            "accessory": "broadlinkSP",
            "name": "Smart Light",
            "mac": "34:EA:34:F5:2E:18"
        }
   ],
   "platforms":[

   ]
}
```

**Comment by syu-lk4b** [comment]
i tested another module called homebridge-broadlink-platform, it works pretty well so far, you may try this one.  At least works fine with my sp3

**Comment by syu-lk4b** [comment]
BTW ,the same author wrote  this module ,not sure what the different between this one to  homebridge-broadlink-platform

**Comment by Ugmaxie** [comment]
I confirm, that this plugin is making Homebridge slow and sets all devices to **Updating/Not responding** status. 
Besides that, `homebridge-broadlink-platform` works perfectly.
Conditions:
- Raspberry Pi 3 B+ with Raspbian@latest
- Homebridge
- installed plugins: `homebridge-broadlink-rm` and was `homebridge-broadlink-sp` (`-platform` now)
- works via Homepod iOS 11.4, iPhone7 on iOS 11.4.

**Comment by iandronowicz** [comment]
The -platform has the same issue: if one of the configured SP's losses wifi connection or is unplugged, it freezes the whole home bridge instance... it should show only THAT SP as offline and let the others work...
